language: php

php:
  - 5.6

before_script:
  - cp .env.example .env
  - mysql -uroot -e 'create database specie;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - vendor/bin/phpunit
